#cloud-config

package_update: true
package_upgrade: true

ssh:
  emit_keys_to_console: false

no_ssh_fingerprints: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

write_files:
  - path: /etc/systemd/system/ttyd.service
    content: |
      [Unit]
      Description=TTYD
      After=syslog.target
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/ttyd --ssl --ssl-cert /etc/ttyd/certs/server.crt --ssl-key /etc/ttyd/certs/server.key --ssl-ca /etc/ttyd/certs/ca.crt login
      Type=simple
      Restart=always
      User=root
      Group=root

      [Install]
      WantedBy=multi-user.target
    owner: 'root:root'
    permissions: '0644'    
  - path: /tmp/san.txt
    content: |
      subjectAltName=DNS:localhost
    owner: 'root:root'
    permissions: '0644'    

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    kubernetes.list:
      source: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
      keyid: 59FE0256827269DC81578F928B57C5C2836F4BEB
    helm-stable-debian.list:
      source: deb [arch=amd64] https://baltocdn.com/helm/stable/debian/ all main
      keyid: 81BF832E2F19CD2AA0471959294AC4827C1A168A

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - wget
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - net-tools
  - kubectl
  - inetutils-traceroute
  - zip
  - jq
  - zsh
  - bash-completion
  - helm

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/sdb
    filesystem: ext4
    partition: 1

mounts:
  - [ /dev/sdb1, /data, "auto", "defaults,noexec,nofail" ]

runcmd:
  - curl -ks https://192.168.11.20/wcp/plugin/linux-amd64/vsphere-plugin.zip -o /tmp/vsphere-plugin.zip
  - unzip -qn /tmp/vsphere-plugin.zip -d /tmp
  - install /tmp/bin/kubectl-vsphere /usr/local/bin
  - runuser -l ubuntu -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  - chsh -s $(which zsh) ubuntu 
  - runuser -l ubuntu -c 'sed -i "s/ZSH_THEME=\"robbyrussell\"/ZSH_THEME=\"agnoster\"/" .zshrc'
  - wget https://github.com/vmware/govmomi/releases/download/v0.27.2/govc_Linux_x86_64.tar.gz -O /tmp/govc_Linux_x86_64.tar.gz
  - tar -xzvf /tmp/govc_Linux_x86_64.tar.gz -C /tmp
  - install /tmp/govc /usr/local/bin 
  - wget https://github.com/vmware-tanzu/pinniped/releases/download/v0.12.0/pinniped-cli-linux-amd64 -O /tmp/pinniped
  - install /tmp/pinniped /usr/local/bin
  - wget -O- https://carvel.dev/install.sh | bash
  - wget https://github.com/vmware-tanzu/velero/releases/download/v1.7.0/velero-v1.7.0-linux-amd64.tar.gz -O /tmp/velero-v1.7.0-linux-amd64.tar.gz
  - tar -xzvf /tmp/velero-v1.7.0-linux-amd64.tar.gz -C /tmp
  - install /tmp/velero-v1.7.0-linux-amd64/velero /usr/local/bin 
  - wget https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64 -O /tmp/ttyd
  - install /tmp/ttyd /usr/local/bin
  - mkdir -p /etc/ttyd/certs
  - openssl genrsa -out /etc/ttyd/certs/ca.key 2048
  - openssl req -new -x509 -days 365 -key /etc/ttyd/certs/ca.key -subj "/C=US/ST=CA/L=SF/O=VMware/CN=TTYD Root CA" -out /etc/ttyd/certs/ca.crt
  - openssl req -newkey rsa:2048 -nodes -keyout /etc/ttyd/certs/server.key -subj "/C=US/ST=CA/L=SF/O=VMware/CN=localhost" -out /etc/ttyd/certs/server.csr
  - openssl x509 -sha256 -req -extfile /tmp/san.txt -days 365 -in /etc/ttyd/certs/server.csr -CA /etc/ttyd/certs/ca.crt -CAkey /etc/ttyd/certs/ca.key -CAcreateserial -out /etc/ttyd/certs/server.crt
  - systemctl start ttyd && sudo systemctl enable ttyd